# Generated by Django 5.1 on 2024-08-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentorcd', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('mentorname', models.TextField()),
                ('mentoremail', models.EmailField(default='default@example.com', max_length=254)),
            ],
        ),
    ]
